name: CI / CD
on: push

jobs:
  npm-ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with: {node-version: 10.x}
      - name: npm-install
        run:  npm install
      - name: npm-lint
        run:  npm run lint
      - name: npm-build
        run:  npm build
      - name: npm-test
        uses: paambaati/codeclimate-action@v2.2.1
        env:
          CC_TEST_REPORTER_ID: ${{secrets.cc_token}}
        with:
          coverageCommand: npm run test
      - name: npm-meta
        if:   github.ref == 'master'
        run:  npm run meta
      - name: npm-docs
        if:   github.ref == 'master'
        run:  npm run docs
      - name: gh-pages
        if:   github.ref == 'master'
        uses: maxheld83/ghpages@v0.2.1
        with:
          GH_PAT: ${{secrets.gh_pages_token}}
        env:
          BUILD_DIR: docs/
      - name: npm-publish
        if:   github.event.ref_type == 'tag'
        run: |
          npm version from-git
          npm publish
